insert into category (id, name, parent_id) values (1, 'Другие услуги', null);
insert into category (id, name, parent_id) values (2, 'Домашний мастер', null);
insert into category (id, name, parent_id) values (3, 'Клининговые услуги', null);
insert into category (id, name, parent_id) values (4, 'Курьерские услуги', null);
insert into category (id, name, parent_id) values (5, 'Бюро переводов', null);
insert into category (id, name, parent_id) values (6, 'Мебельные работы', null);
insert into category (id, name, parent_id) values (7, 'Ремонт техники', null);
insert into category (id, name, parent_id) values (8, 'Бытовые услуги', null);
insert into category (id, name, parent_id) values (9, 'Отделочные работы', null);
insert into category (id, name, parent_id) values (10, 'Строительные работы', null);
insert into category (id, name, parent_id) values (11, 'Фото- и видео- услуги', null);
insert into category (id, name, parent_id) values (12, 'Дизайн', null);
insert into category (id, name, parent_id) values (13, 'Работа в Интернете', null);
insert into category (id, name, parent_id) values (14, 'Реклама и маркетинг', null);
insert into category (id, name, parent_id) values (15, 'Разработка сайтов и приложений', null);
insert into category (id, name, parent_id) values (16, 'Логистические и складские услуги', null);
insert into category (id, name, parent_id) values (17, 'Услуги для животных', null);
insert into category (id, name, parent_id) values (18, 'Организация праздников', null);
insert into category (id, name, parent_id) values (19, 'Услуги репетиторов', null);
insert into category (id, name, parent_id) values (20, 'Услуги тренеров', null);
insert into category (id, name, parent_id) values (21, 'Услуги красоты и здоровья', null);
insert into category (id, name, parent_id) values (22, 'Деловые услуги', null);
insert into category (id, name, parent_id) values (23, 'Ремонт авто', null);

insert into category (id, name, parent_id) values (24, 'Сантехник', 2);
insert into category (id, name, parent_id) values (25, 'Электрик', 2);
insert into category (id, name, parent_id) values (26, 'Муж на час', 2);
insert into category (id, name, parent_id) values (27, 'Столяр', 2);
insert into category (id, name, parent_id) values (28, 'Установка бытовой техники', 2);
insert into category (id, name, parent_id) values (29, 'Другие услуги мастера', 2);

insert into category (id, name, parent_id) values (30, 'Уборка квартир', 3);
insert into category (id, name, parent_id) values (31, 'Генеральная уборка', 3);
insert into category (id, name, parent_id) values (32, 'Уборка после ремонта', 3);
insert into category (id, name, parent_id) values (33, 'Уборка офисов', 3);
insert into category (id, name, parent_id) values (34, 'Мойка окон', 3);
insert into category (id, name, parent_id) values (35, 'Химчистка', 3);
insert into category (id, name, parent_id) values (36, 'Уборка ресторанов', 3);
insert into category (id, name, parent_id) values (37, 'Дезинсекция', 3);
insert into category (id, name, parent_id) values (38, 'Уборка коттеджей и домов', 3);
insert into category (id, name, parent_id) values (39, 'Эко-уборка', 3);
insert into category (id, name, parent_id) values (40, 'Уборка магазинов', 3);
insert into category (id, name, parent_id) values (41, 'Уборка прилегающих территорий', 3);
insert into category (id, name, parent_id) values (42, 'Дезинфекция помещений', 3);
insert into category (id, name, parent_id) values (43, 'Мойка фасадов', 3);
insert into category (id, name, parent_id) values (44, 'Дератизация', 3);
insert into category (id, name, parent_id) values (45, 'Уборка производственных помещений', 3);
insert into category (id, name, parent_id) values (46, 'Другая уборка', 3);

insert into category (id, name, parent_id) values (47, 'Курьерская доставка', 4);
insert into category (id, name, parent_id) values (48, 'Доставка документов', 4);
insert into category (id, name, parent_id) values (49, 'Курьер на авто', 4);
insert into category (id, name, parent_id) values (50, 'Доставка подарков', 4);
insert into category (id, name, parent_id) values (51, 'Доставка товара из интернет-магазина', 4);
insert into category (id, name, parent_id) values (52, 'Доставка продуктов и готовой еды', 4);
insert into category (id, name, parent_id) values (53, 'Доставка лекарств', 4);
insert into category (id, name, parent_id) values (54, 'Доставка цветов', 4);
insert into category (id, name, parent_id) values (55, 'Отправить поездом или маршруткой', 4);
insert into category (id, name, parent_id) values (56, 'Забрать и отправить почтой', 4);
insert into category (id, name, parent_id) values (57, 'Найти', 4);
insert into category (id, name, parent_id) values (58, 'Постоять в очереди', 4);
insert into category (id, name, parent_id) values (59, 'Другие курьерские услуги', 4);

insert into category (id, name, parent_id) values (60, 'Письменные переводы', 5);
insert into category (id, name, parent_id) values (61, 'Редактура перевода', 5);
insert into category (id, name, parent_id) values (62, 'Перевод документов и нотариальное заверение', 5);
insert into category (id, name, parent_id) values (63, 'Устные переводы', 5);
insert into category (id, name, parent_id) values (64, 'Технический перевод', 5);
insert into category (id, name, parent_id) values (65, 'Перевод веб-сайтов', 5);
insert into category (id, name, parent_id) values (66, 'Перевод аудио и видео', 5);
insert into category (id, name, parent_id) values (67, 'Апостиль и легализация', 5);
insert into category (id, name, parent_id) values (68, 'Другой перевод', 5);

insert into category (id, name, parent_id) values (69, 'Изготовление мебели', 6);
insert into category (id, name, parent_id) values (70, 'Ремонт мебели', 6);
insert into category (id, name, parent_id) values (71, 'Сборка мебели', 6);
insert into category (id, name, parent_id) values (72, 'Реставрация мебели', 6);
insert into category (id, name, parent_id) values (73, 'Перетяжка мебели', 6);
insert into category (id, name, parent_id) values (74, 'Швея мягкой мебели', 6);
insert into category (id, name, parent_id) values (75, 'Другие мебельные работы', 6);

insert into category (id, name, parent_id) values (76, 'Ремонт крупной бытовой техники', 7);
insert into category (id, name, parent_id) values (77, 'Ремонт мелкой бытовой техники', 7);
insert into category (id, name, parent_id) values (78, 'Компьютерная помощь', 7);
insert into category (id, name, parent_id) values (79, 'Ремонт цифровой техники', 7);
insert into category (id, name, parent_id) values (80, 'Обслуживание техники', 7);
insert into category (id, name, parent_id) values (81, 'Ремонт оргтехники', 7);
insert into category (id, name, parent_id) values (82, 'Ремонт техники для красоты и ухода', 7);
insert into category (id, name, parent_id) values (83, 'Ремонт электроинструментов ', 7);
insert into category (id, name, parent_id) values (84, 'Ремонт медтехники', 7);
insert into category (id, name, parent_id) values (85, 'Ремонт садово-парковой техники', 7);
insert into category (id, name, parent_id) values (86, 'Установка и ремонт систем безопасности', 7);
insert into category (id, name, parent_id) values (87, 'Другой ремонт техники', 7);

insert into category (id, name, parent_id) values (88, 'Няни', 8);
insert into category (id, name, parent_id) values (89, 'Услуги сиделки', 8);
insert into category (id, name, parent_id) values (90, 'Услуги швеи', 8);
insert into category (id, name, parent_id) values (91, 'Ремонт обуви', 8);
insert into category (id, name, parent_id) values (92, 'Услуги повара', 8);
insert into category (id, name, parent_id) values (93, 'Стирка и глажка вещей', 8);
insert into category (id, name, parent_id) values (94, 'Ремонт сумок', 8);
insert into category (id, name, parent_id) values (95, 'Покраска одежды', 8);
insert into category (id, name, parent_id) values (96, 'Сад и огород', 8);
insert into category (id, name, parent_id) values (97, 'Ремонт велосипедов', 8);
insert into category (id, name, parent_id) values (98, 'Заточка инструментов', 8);
insert into category (id, name, parent_id) values (99, 'Ремонт ювелирных изделий', 8);
insert into category (id, name, parent_id) values (100, 'Ремонт часов', 8);
insert into category (id, name, parent_id) values (101, 'Другие бытовые услуги', 8);

insert into category (id, name, parent_id) values (102, 'Ремонт квартир', 9);
insert into category (id, name, parent_id) values (103, 'Укладка плитки', 9);
insert into category (id, name, parent_id) values (104, 'Штукатурные работы', 9);
insert into category (id, name, parent_id) values (105, 'Монтаж гипсокартона', 9);
insert into category (id, name, parent_id) values (106, 'Малярные работы', 9);
insert into category (id, name, parent_id) values (107, 'Поклейка обоев', 9);
insert into category (id, name, parent_id) values (108, 'Напольные работы', 9);
insert into category (id, name, parent_id) values (109, 'Установка и ремонт дверей', 9);
insert into category (id, name, parent_id) values (110, 'Полировка мрамора', 9);
insert into category (id, name, parent_id) values (111, 'Установка и ремонт окон', 9);
insert into category (id, name, parent_id) values (112, 'Демонтажные работы', 9);
insert into category (id, name, parent_id) values (113, 'Фасадные работы', 9);
insert into category (id, name, parent_id) values (114, 'Потолочные работы', 9);
insert into category (id, name, parent_id) values (115, 'Работа со стеклом', 9);
insert into category (id, name, parent_id) values (116, 'Звукоизоляция', 9);
insert into category (id, name, parent_id) values (117, 'Монтаж вагонки', 9);
insert into category (id, name, parent_id) values (118, 'Другие ремонтные работы', 9);

insert into category (id, name, parent_id) values (119, 'Разнорабочие', 10);
insert into category (id, name, parent_id) values (120, 'Сварочные работы', 10);
insert into category (id, name, parent_id) values (121, 'Токарные работы', 10);
insert into category (id, name, parent_id) values (122, 'Плотник', 10);
insert into category (id, name, parent_id) values (123, 'Кладка кирпича', 10);
insert into category (id, name, parent_id) values (124, 'Установка заборов и ворот', 10);
insert into category (id, name, parent_id) values (125, 'Кровельные работы', 10);
insert into category (id, name, parent_id) values (126, 'Бетонные работы', 10);
insert into category (id, name, parent_id) values (127, 'Буровые работы', 10);
insert into category (id, name, parent_id) values (128, 'Фундаментные работы', 10);
insert into category (id, name, parent_id) values (129, 'Строительство домов', 10);
insert into category (id, name, parent_id) values (130, 'Строительство мелких конструкций', 10);
insert into category (id, name, parent_id) values (131, 'Ландшафтные работы', 10);
insert into category (id, name, parent_id) values (132, 'Архитектура и проектирование', 10);
insert into category (id, name, parent_id) values (133, 'Составление смет', 10);
insert into category (id, name, parent_id) values (134, 'Земляные работы', 10);
insert into category (id, name, parent_id) values (135, 'Монтаж вентиляции', 10);
insert into category (id, name, parent_id) values (136, 'Промышленный альпинизм', 10);
insert into category (id, name, parent_id) values (137, 'Другие стройработы', 10);

insert into category (id, name, parent_id) values (138, 'Фотограф', 11);
insert into category (id, name, parent_id) values (139, 'Видеооператор', 11);
insert into category (id, name, parent_id) values (140, 'Обработка фотографий', 11);
insert into category (id, name, parent_id) values (141, 'Монтаж видео', 11);
insert into category (id, name, parent_id) values (142, 'Оцифровка видеокассет', 11);
insert into category (id, name, parent_id) values (143, 'Аэросъемка', 11);
insert into category (id, name, parent_id) values (144, 'Выпускные альбомы', 11);
insert into category (id, name, parent_id) values (145, 'Другие услуги фото и видео', 11);

insert into category (id, name, parent_id) values (146, 'Разработка логотипов', 12);
insert into category (id, name, parent_id) values (147, 'Дизайн интерьера', 12);
insert into category (id, name, parent_id) values (148, 'Дизайн сайта', 12);
insert into category (id, name, parent_id) values (149, 'Дизайн полиграфии', 12);
insert into category (id, name, parent_id) values (150, 'Услуги печати', 12);
insert into category (id, name, parent_id) values (151, 'Рисунки и иллюстрации', 12);
insert into category (id, name, parent_id) values (152, 'Дизайн баннеров', 12);
insert into category (id, name, parent_id) values (153, '3D дизайн', 12);
insert into category (id, name, parent_id) values (154, 'Разработка инфографики', 12);
insert into category (id, name, parent_id) values (155, 'UX/UI дизайн', 12);
insert into category (id, name, parent_id) values (156, 'Другое в дизайне', 12);

insert into category (id, name, parent_id) values (157, 'Копирайтинг', 13);
insert into category (id, name, parent_id) values (158, 'Сбор, поиск информации', 13);
insert into category (id, name, parent_id) values (159, 'Наполнение сайтов', 13);
insert into category (id, name, parent_id) values (160, 'Набор текста', 13);
insert into category (id, name, parent_id) values (161, 'Рерайтинг', 13);
insert into category (id, name, parent_id) values (162, 'Ввод данных', 13);
insert into category (id, name, parent_id) values (163, 'Расшифровка интервью', 13);
insert into category (id, name, parent_id) values (164, 'Создание презентаций', 13);
insert into category (id, name, parent_id) values (165, 'Другая онлайн работа', 13);

insert into category (id, name, parent_id) values (166, 'Реклама в Интернете', 14);
insert into category (id, name, parent_id) values (167, 'Распространение рекламы', 14);
insert into category (id, name, parent_id) values (168, 'Изготовление и монтаж наружной рекламы', 14);
insert into category (id, name, parent_id) values (169, 'Услуги промоутеров', 14);
insert into category (id, name, parent_id) values (170, 'Услуги звукорежиссера', 14);
insert into category (id, name, parent_id) values (171, 'Услуги модели', 14);
insert into category (id, name, parent_id) values (172, 'Другая реклама', 14);

insert into category (id, name, parent_id) values (173, 'Создание сайтов', 15);
insert into category (id, name, parent_id) values (174, 'Доработка сайта', 15);
insert into category (id, name, parent_id) values (175, 'Создание Landing page', 15);
insert into category (id, name, parent_id) values (176, 'Продвижение сайтов', 15);
insert into category (id, name, parent_id) values (177, 'Верстка сайта', 15);
insert into category (id, name, parent_id) values (178, 'Тестирование ПО (QA)', 15);
insert into category (id, name, parent_id) values (179, 'Внедрение 1C', 15);
insert into category (id, name, parent_id) values (180, 'Услуги в сфере IT', 15);
insert into category (id, name, parent_id) values (181, 'Разработка мобильных приложений', 15);
insert into category (id, name, parent_id) values (182, 'Создание и разработка технического задания', 15);
insert into category (id, name, parent_id) values (183, 'Другие работы по разработке сайтов', 15);

insert into category (id, name, parent_id) values (184, 'Грузоперевозки', 16);
insert into category (id, name, parent_id) values (185, 'Услуги грузчиков', 16);
insert into category (id, name, parent_id) values (186, 'Вывоз строительного мусора', 16);
insert into category (id, name, parent_id) values (187, 'Перевозка мебели и техники', 16);
insert into category (id, name, parent_id) values (188, 'Переезд квартиры или офиса', 16);
insert into category (id, name, parent_id) values (189, 'Услуги такси', 16);
insert into category (id, name, parent_id) values (190, 'Трезвый водитель', 16);
insert into category (id, name, parent_id) values (191, 'Пассажирские перевозки', 16);
insert into category (id, name, parent_id) values (192, 'Междугородняя перевозка', 16);
insert into category (id, name, parent_id) values (193, 'Упаковка и сортировка', 16);
insert into category (id, name, parent_id) values (194, 'Услуги склада', 16);
insert into category (id, name, parent_id) values (195, 'Международная перевозка', 16);
insert into category (id, name, parent_id) values (196, 'Вывоз снега', 16);
insert into category (id, name, parent_id) values (197, 'Таможенное оформление', 16);
insert into category (id, name, parent_id) values (198, 'Услуги экспедитора', 16);
insert into category (id, name, parent_id) values (199, 'Другие логистические и складские услуги', 16);

insert into category (id, name, parent_id) values (200, 'Уход за котами', 17);
insert into category (id, name, parent_id) values (201, 'Уход за собаками', 17);
insert into category (id, name, parent_id) values (202, 'Гостиница для животных', 17);
insert into category (id, name, parent_id) values (203, 'Перевозка животных', 17);
insert into category (id, name, parent_id) values (204, 'Уход за рыбками', 17);
insert into category (id, name, parent_id) values (205, 'Уход за грызунами', 17);
insert into category (id, name, parent_id) values (206, 'Уход за птицами', 17);
insert into category (id, name, parent_id) values (207, 'Уход за рептилиями', 17);
insert into category (id, name, parent_id) values (208, 'Другие зооуслуги', 17);

insert into category (id, name, parent_id) values (209, 'Услуги ведущего', 18);
insert into category (id, name, parent_id) values (210, 'Музыкальное сопровождение', 18);
insert into category (id, name, parent_id) values (211, 'Услуги аниматоров', 18);
insert into category (id, name, parent_id) values (212, 'Организация питания', 18);
insert into category (id, name, parent_id) values (213, 'Выпечка и десерты', 18);
insert into category (id, name, parent_id) values (214, 'Персонал для мероприятий', 18);
insert into category (id, name, parent_id) values (215, 'Оформление праздников', 18);
insert into category (id, name, parent_id) values (216, 'Праздник под ключ', 18);
insert into category (id, name, parent_id) values (217, 'Другие ивент услуги', 18);

insert into category (id, name, parent_id) values (218, 'Преподаватели по предметам', 19);
insert into category (id, name, parent_id) values (219, 'Репетиторы иностранных языков', 19);
insert into category (id, name, parent_id) values (220, 'Написание работ', 19);
insert into category (id, name, parent_id) values (221, 'Преподаватели музыки', 19);
insert into category (id, name, parent_id) values (222, 'Автоинструкторы', 19);
insert into category (id, name, parent_id) values (223, 'Другие репетиторы', 19);

insert into category (id, name, parent_id) values (224, 'Йога', 20);
insert into category (id, name, parent_id) values (225, 'Групповой фитнес', 20);
insert into category (id, name, parent_id) values (226, 'Игровые виды спорта', 20);
insert into category (id, name, parent_id) values (227, 'Водные виды спорта', 20);
insert into category (id, name, parent_id) values (228, 'Боевые искусства', 20);
insert into category (id, name, parent_id) values (229, 'Силовые виды спорта', 20);
insert into category (id, name, parent_id) values (230, 'Зимние виды спорта', 20);
insert into category (id, name, parent_id) values (231, 'Хореография', 20);
insert into category (id, name, parent_id) values (232, 'Другие виды спорта', 20);

insert into category (id, name, parent_id) values (233, 'Массаж', 21);
insert into category (id, name, parent_id) values (234, 'Уход за ногтями', 21);
insert into category (id, name, parent_id) values (235, 'Косметология', 21);
insert into category (id, name, parent_id) values (236, 'Уход за ресницами', 21);
insert into category (id, name, parent_id) values (237, 'Уход за бровями', 21);
insert into category (id, name, parent_id) values (238, 'Парикмахерские услуги', 21);
insert into category (id, name, parent_id) values (239, 'Депиляция', 21);
insert into category (id, name, parent_id) values (240, 'Услуги визажиста-стилиста', 21);
insert into category (id, name, parent_id) values (241, 'Макияж', 21);
insert into category (id, name, parent_id) values (242, 'Психолог', 21);
insert into category (id, name, parent_id) values (243, 'Диетолог', 21);
insert into category (id, name, parent_id) values (244, 'Другой уход за собой', 21);

insert into category (id, name, parent_id) values (245, 'Бухгалтерские услуги', 22);
insert into category (id, name, parent_id) values (246, 'Юридические услуги', 22);
insert into category (id, name, parent_id) values (247, 'Риэлтор', 22);
insert into category (id, name, parent_id) values (248, 'Услуги колл-центра', 22);
insert into category (id, name, parent_id) values (249, 'Финансовые услуги', 22);
insert into category (id, name, parent_id) values (250, 'Консалтинговые услуги', 22);
insert into category (id, name, parent_id) values (251, 'Кадровые услуги', 22);
insert into category (id, name, parent_id) values (252, 'Услуги безопасности', 22);
insert into category (id, name, parent_id) values (253, 'Услуги в сфере миграции', 22);
insert into category (id, name, parent_id) values (254, 'Другие деловые услуги', 22);

insert into category (id, name, parent_id) values (255, 'Помощь в дороге', 23);
insert into category (id, name, parent_id) values (256, 'Техническое обслуживание и диагностика', 23);
insert into category (id, name, parent_id) values (257, 'Автоэлектрика', 23);
insert into category (id, name, parent_id) values (258, 'Кузовные работы', 23);
insert into category (id, name, parent_id) values (259, 'Двигатель', 23);
insert into category (id, name, parent_id) values (260, 'Коробка переключения передач', 23);
insert into category (id, name, parent_id) values (261, 'Уход за салоном', 23);
insert into category (id, name, parent_id) values (262, 'Ремонт и замена автостекол', 23);
insert into category (id, name, parent_id) values (263, 'Ходовая часть', 23);
insert into category (id, name, parent_id) values (264, 'Рулевая система', 23);
insert into category (id, name, parent_id) values (265, 'Тормозная система', 23);
insert into category (id, name, parent_id) values (266, 'Выхлопная система', 23);
insert into category (id, name, parent_id) values (267, 'Шиномонтаж', 23);
insert into category (id, name, parent_id) values (268, 'Ремонт и обслуживание автокондиционеров', 23);
insert into category (id, name, parent_id) values (269, 'Установка газобаллонного оборудования (ГБО)', 23);
insert into category (id, name, parent_id) values (270, 'Ремонт мототехники', 23);
insert into category (id, name, parent_id) values (271, 'Автострахование', 23);
insert into category (id, name, parent_id) values (272, 'Другой ремонт авто', 23);

insert into category (id, name, parent_id) values (273, 'Другое', 1);